class Document < ApplicationRecord
  belongs_to :user
  
  validates :text, presence: true
  
  # Store pictograms as JSON
  attribute :pictos_json, :json, default: []
  
  # Simplified text can be generated by the Python microservice
  validates :text, length: { minimum: 1 }
end
