source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.2.0'

# Rails framework
gem 'rails', '~> 7.0.8'

# Database
gem 'sqlite3', '~> 1.4'

# Web server
gem 'puma', '~> 5.0'

# Authentication
gem 'devise', '~> 4.9'
gem 'devise-jwt', '~> 0.11.0'

# CORS
gem 'rack-cors'

# HTTP client for external API calls
gem 'httparty', '~> 0.21'

# Build JSON APIs
gem 'jbuilder'

# Windows timezone support
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
end

group :development do
  # Speed up commands on slow machines
  gem 'spring'
end
